### ISSUE TITLE
Can't edit technology without filling out licence information

### ISSUE THREAD

**Issue by piotrgo** [KainosSoftwareLtd/TechRadar#34]
Whenever you want to edit existing technology you have to provide a "Licence details" link even if it was empty before your changes.

**Comment by piotrgo** [comment]
However adding a technology doesn't require that field to be filled in.

**Comment by adrianz-kainos** [comment]
@gpimblott  
It's caused by line 76 from editTechnology.ejs: 
https://github.com/KainosSoftwareLtd/TechRadar/blob/master/views/pages/editTechnology.ejs#L76
`value="<%= (technology.licencelink == null ? "http://" : technology.licencelink) %>"`
The default value: `http://` triggers a validation error. Should we get rid of it or is it intended?
